### ISSUE TITLE
How to manual-init & overwrite config-settings?

### ISSUE THREAD

**Issue by xstable** [thriveweb/yellowcake#38]
I try to overwrite config-settings from netlify-cms ⇒ config.yml.

I've found some documentations, that I could do it if I set `manualInit: true,` to gatsby.config like this: 
```
  'gatsby-plugin-sitemap',
    {
      resolve: 'gatsby-plugin-netlify-cms',
      options: {
        modulePath: `${__dirname}/src/cms/cms.js`,
        stylesPath: `${__dirname}/src/cms/admin.css`,
        enableIdentityWidget: false
      }
    },
```
And call init manually like described here: https://www.gatsbyjs.org/packages/gatsby-plugin-netlify-cms/#manualinit

I've checkd it with changing 
```
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

```
with
```
backend:
  name: gitlab
  repo: xxxx/gatsby_netlifycms_starter
  auth_type: implicit
  app_id: 2xxxxxxxxxxc359
```
But I don't get it to work. Config was never overwritten.
Any Idea, why? 

https://github.com/thriveweb/yellowcake/blob/f779e583fce994a544fa1f5c9115779c88fc2f07/src/cms/cms.js#L12
